### ISSUE TITLE
Resolving the /docs page. 

### ISSUE THREAD

**Issue by Gitstar-OC** [gkamradt/gregkamradtdotcom#1]
Hey @gkamradt, I saw that you asked fumaname about this [issue](https://github.com/fuma-nama/fumadocs/discussions/892) and I guessed that the issue might be for this repository that you are trying to make and when I opened the website. Was the issue in any other website ?

**Comment by gkamradt** [comment]
It was actually for this website

https://www.leverage.to/learn

and I got it working with the "/learn"

**Comment by Gitstar-OC** [comment]
Is it open source ? Actually I also need to change the path from /docs to /learn, can you add me as a collaborator on your repository or guide me through what you did. 

Thanks in Advance!

**Comment by gkamradt** [comment]
It's not, it might be in the future, but isn't right now.

this is the important part though.

1) Add learn page to your (home)
2) change docs > learn in app/
3) change content/docs > content/learn (this is preference but I wanted to for consistency)
4) in your source.config.ts give a custom directory for both docs/meta to point towards the non-default content/learn

<img width="791" alt="image" src="https://github.com/user-attachments/assets/3b629718-84c4-4ab7-8dc2-d3da200f594c">

**Comment by Gitstar-OC** [comment]
Thanks, That helped a lot as I also have a learning app !!

**Comment by Gitstar-OC** [comment]
Hello @gkamradt, but now there is a problem as I am implementing this, the path is still /docs when I open the docs and want to switch them. I have modified it in the layout.tsx but it is still not working. Also the root toggler is not switching the content properly and showing the complete files at ones (including the sub folders) 

Could I please see the codebase of the app and modifications you have done. It would help me a lot and save hours of time for me.

**Comment by Gitstar-OC** [comment]
You can see the code base in [here](https://github.com/Gitstar-OC/mindect/tree/learn).

**Comment by gkamradt** [comment]
Hey! Not sure what's going on. My site isn't open sourced yet and might be later.

Does options throw a fit cause you're putting a component in the object here?
https://github.com/Gitstar-OC/mindect/blob/2900cbfc82237288ef9e4ed4220f2b4165fa8341/app/learn/layout.tsx#L21

Either way, on first glance it looks like you have everything set up like how I'd expect so not sure what's going on. Please raise an issue on fumadocs instead of here if you want to continue the conversation

**Comment by Gitstar-OC** [comment]
Alright, I will post issue on the fumadocs, it would have been helpful if I could have seen the code and configurations because I have asked it to fuma-nama and he is not willing to focus on it as it is just for docs. 

Putting component in the icons place work, there are no errors in the terminal or console.

**Comment by Gitstar-OC** [comment]
Also thanks for checking out.

**Comment by Gitstar-OC** [comment]
Thanks it worked out properly along with the 4 steps we also need to change the path in the source.ts file which I had not setup. Thanks
